coverage:
  status:
    project:
      default:
        target: 90%  # we want at least 90% coverage in Collie
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 5%  # PR may only decrease test coverage by up to 5%
        if_ci_failed: error
